service: web3-vault-api
useDotenv: true

plugins:
  - serverless-offline
  
provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  memorySize: 512
  timeout: 30
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    DATABASE_AUTH_TOKEN: ${env:DATABASE_AUTH_TOKEN}
    JWT_SECRET: ${env:JWT_SECRET}
    ENCRYPTION_KEY: ${env:ENCRYPTION_KEY}
    IOTA_NODES: ${env:IOTA_NODES}
    
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'

  ecr:
    images:
        app:
          path: .

functions:
  api:
    image: app
    
    timeout: 300 # 5 minutes
    events:
      - http:
          path: "{proxy+}"
          method: ANY

    


