service: web3-vault-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  memorySize: 512
  timeout: 30
  architecture: arm64
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    DATABASE_AUTH_TOKEN: ${env:DATABASE_AUTH_TOKEN}
    JWT_SECRET: ${env:JWT_SECRET}
    ENCRYPTION_KEY: ${env:ENCRYPTION_KEY}
    IOTA_NODES: ${env:IOTA_NODES}
    
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
  iam:
      role:
        name: lambda-web3-vault-${opt:stage}-role
        statements:
          - Effect: "Allow"
            Action:
              - "s3:*"
            Resource: "*"


functions:
  api:
    handler: dist/function.handler
    timeout: 300 # 5 minutes
    events:
      - http:
          path: "{proxy+}"
          method: ANY

    


